# Header

menu:
  主页: /
  日常: /tags/日常/
  BiLiBiLi弹幕解密器: https://bilibili.zscself.com/
  网站地图: /sitemap.xml


# SubNav
subnav:
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  github: "https://github.com/firedent"
  #cc:
  wikipedia: "https://zh.moegirl.org/User:Zscself"
  #gitlab:
  steam: "https://steamcommunity.com/profiles/76561198107245108"
  #youtube: 
  #stackoverflow:
  #whatsapp:
  #instagram:
  telegram: "https://telegram.me/DuDuLuDuDaDaDa"
  mail: "/mail.png"
  #gitlab:

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 
# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '阅读全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/donateMeByAlipay.jpg
# 微信二维码图片地址
# weixin: 

# Miscellaneous
baidu_analytics: '1a20d4b1772a9c03105309df5ceef184'
google_analytics: ''
favicon: /frog.png

#你的头像url
avatar: https://ojewiybay.qnssl.com/yilianmengbi.jpg

#是否开启分享
share_jia: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: fir3d3nt

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#F9690E'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#F4B350,#E87E04)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于'
friends:
  谁佛: http://sheifo.com/
aboutme: 这里是F!redent的个人网站<br>湿货多和啰哩啰嗦<br>是本站的两大特点<br>喜欢不会给你带来什么<br>不喜欢也不会让我失去什么<br>要做就做真实的自己<br><br><br>很惭愧<br><br>只做了一点微小的工作<br>谢谢大家

# 版权声明
# 请在需要进行版权声明的文章的md文件头部，设置属性declare: true
# 版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
declare_type: 1
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'
licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png

