# Header

menu:
  主页: /
  2018年计划: /posts/13f2871/
  BiLiBiLi弹幕解密器: https://bilibili.zscself.com/
  公钥(4492E554): /download/4492E554–Public.asc
  网站地图: /sitemap.xml

# SubNav
subnav:
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  github: "https://github.com/firedent"
  #cc:
  ##wikipedia: "https://zh.moegirl.org/User:Zscself"
  #gitlab:
  steam: "https://steamcommunity.com/profiles/76561198107245108"
  #youtube:
  #stackoverflow:
  #whatsapp:
  #instagram:
  telegram: "https://telegram.me/DuDuLuDuDaDaDa"
  rss: /feed.xml
  mail: "/mail.png"
  #gitlab:

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /
# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '阅读全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '大家好，我以前是一名任豚，现在已趋入索尼神教，准备去日本参加入教仪式。往返机票食宿总共2500元，接受支付宝转账，希望好心人圆我一个梦想。
我不知道什么是Nintendo Switch，更不知道什么塞尔达。'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/donateMeByAlipay.gif
# 微信二维码图片地址
# weixin:

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '10d5995ba60a44948e3bf579c6065e10'
google_analytics: 'UA-92400662-1'
google_adsense: 'ca-pub-5449073639010251'
favicon: /images/frog.png

#你的头像url
avatar: /images/yilianmengbi.jpg

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: 'firet'
disqusjs:
    siteName: 'F!redent'
    api: ''
    apikey: 'wsQ74y9hNqCCErZJ0l6P9pMnAhjylWkkjcoQqL0NRscjXWchIxdUBTFQxzVhcKyS'
    admin: 'Fir3d3nt'
    adminLabel: '站长大人'

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#F9690E'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#F4B350,#E87E04)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  archives: '归档'
  aboutme: '关于'
archives:
  2019年 (๑•̀ㅂ•́)و✧: /archives/2019
  2018年 ￣ω￣=: /archives/2018
  2017年 ╮(╯_╰)╭: /archives/2017
  2016年 (ಥ_ಥ): /archives/2016
  2015年 φ(≧ω≦*)♪: /archives/2015
  2014年 ヾ(=･ω･=)o: /archives/2014
friends:
  谁佛: http://sheifo.com/
aboutme: 这里是F!redent的个人网站<br>始于2014-09-12<br>湿货多和啰哩啰嗦是本站的两大特点。<br><br>很惭愧<br>只做了一点微小的工作<br><br>谢谢大家

# 版权声明
# 请在需要进行版权声明的文章的md文件头部，设置属性declare: true
# 版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
declare_type: 1
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'
